wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1646062537
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
alpha:
  desc: null
  value: 0.4078263377639245
learning_rate:
  desc: null
  value: 0.014348680245679729
min_samples_leaf:
  desc: null
  value: 9
min_samples_split:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 4823
