wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645118701
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
alpha:
  desc: null
  value: 0.7584399578585892
learning_rate:
  desc: null
  value: 0.00590765940791444
min_samples_leaf:
  desc: null
  value: 2
min_samples_split:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 531
