wandb_version: 1

C:
  desc: null
  value: 3.5807162108323842
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645389570
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
degree:
  desc: null
  value: 1
epsilon:
  desc: null
  value: 0.950774122036756
gamma:
  desc: null
  value: 1.992840830315136
kernel:
  desc: null
  value: poly
