wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645622288
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
covariance_type:
  desc: null
  value: diag
max_iter:
  desc: null
  value: 929
n_components:
  desc: null
  value: 3
