wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645387899
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
alpha_1:
  desc: null
  value: 0.0010394674534503208
alpha_2:
  desc: null
  value: 0.00034923084443938356
fit_intercept:
  desc: null
  value: true
lambda_1:
  desc: null
  value: 0.0020766641871289826
lambda_2:
  desc: null
  value: 0.003674808927146793
n_iter:
  desc: null
  value: 5210
