wandb_version: 1

C:
  desc: null
  value: 0.10559188428752561
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645796623
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
fit_intercept:
  desc: null
  value: false
l1_ratio:
  desc: null
  value: 0.8462483342369894
max_iter:
  desc: null
  value: 89211
multi_class:
  desc: null
  value: multinomial
penalty:
  desc: null
  value: l1
solver:
  desc: null
  value: saga
