wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645989326
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
alpha_1:
  desc: null
  value: 0.0009101898386663006
alpha_2:
  desc: null
  value: 0.009632132065693357
fit_intercept:
  desc: null
  value: true
lambda_1:
  desc: null
  value: 0.009693366559813326
lambda_2:
  desc: null
  value: 0.00672822988740931
n_iter:
  desc: null
  value: 14324
