wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1653663603
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
degree:
  desc: null
  value: 3
gamma:
  desc: null
  value: 1.7656898321327559
kernel:
  desc: null
  value: sigmoid
nu:
  desc: null
  value: 0.019587421263204677
