wandb_version: 1

C:
  desc: null
  value: 0.4862529744880452
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645536693
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
degree:
  desc: null
  value: 2
epsilon:
  desc: null
  value: 0.3726314876919036
gamma:
  desc: null
  value: 0.44796726648937435
kernel:
  desc: null
  value: poly
