wandb_version: 1

C:
  desc: null
  value: 3.9920799763587547
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645185987
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
degree:
  desc: null
  value: 2
epsilon:
  desc: null
  value: 1.6557144463703168
gamma:
  desc: null
  value: 1.4384406486102108
kernel:
  desc: null
  value: poly
