wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1645433383
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
alpha_1:
  desc: null
  value: 0.0028221978862259097
alpha_2:
  desc: null
  value: 0.008990977183821134
fit_intercept:
  desc: null
  value: false
lambda_1:
  desc: null
  value: 0.0011447848034931531
lambda_2:
  desc: null
  value: 0.005731812863334653
n_iter:
  desc: null
  value: 8034
