wandb_version: 1

C:
  desc: null
  value: 3.831069599903173
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1649054499
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
degree:
  desc: null
  value: 2
epsilon:
  desc: null
  value: 0.21405401502660762
gamma:
  desc: null
  value: 1.2023651501646662
kernel:
  desc: null
  value: rbf
