wandb_version: 1

C:
  desc: null
  value: 3.8251929609827564
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1646479890
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
degree:
  desc: null
  value: 2
epsilon:
  desc: null
  value: 0.41845759183980274
gamma:
  desc: null
  value: 0.1144771119296218
kernel:
  desc: null
  value: linear
