wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650538808
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
alpha_1:
  desc: null
  value: 0.007883292458143584
alpha_2:
  desc: null
  value: 0.0021658451344749134
fit_intercept:
  desc: null
  value: true
lambda_1:
  desc: null
  value: 0.005214702401666184
lambda_2:
  desc: null
  value: 0.001436837539727999
n_iter:
  desc: null
  value: 16923
