wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/DD_package/main.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1653942614
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 5
activation:
  desc: null
  value: tanh
hidden_layer_sizes:
  desc: null
  value: 11
max_iter:
  desc: null
  value: 40181
solver:
  desc: null
  value: sgd
